server:
  port: 9100

spring:
  application:
    name: product
  datasource:
    url: jdbc:h2:mem:product;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
#      ddl-auto: validate
#      generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

eureka:
  instance:
    prefer-ip-address: true # OS에서 제공하는 hostname 대신 자신의 ip address를 사용 (local 용)
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka