server:
  port: 9000

spring:
  application:
    name: display
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false #Config Server와 연결이 되지 않아도 실행
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:h2:mem:display;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    #      ddl-auto: validate
    #      generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

management:
  endpoints:
    web:
      exposure:
        include: refresh

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 # default 1000
      circuitBreaker:
        requestVolumeThreshold: 1     # Minimum number of requests in calculate circuit breaker's health. default 20
        errorThresholdPercentage: 50  # Error percentage to open circuit. default 50

product-api:
  ribbon:
    listOfServers: http://localhost:9100,http://localhost:9101
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1 # 실패시 다른 서버로 재시도하는 횟수
